### ISSUE TITLE
Setting "path" option no longer works

### ISSUE THREAD

**Issue by bennettrogers** [django-webpack/webpack-bundle-tracker#108]
It seems that setting the `path` option in the BundleTracker options no longer has an effect. I think the issue was introduced in [this commit](https://github.com/django-webpack/webpack-bundle-tracker/commit/51dfab5759c2b72d68cd5728b56c64e11e992f41). Regardless of what the `path` option is set to, the stats file is rooted in the cwd.

It's possible to work around the issue by specifying the full file path in the `filename` option.

**Comment by fjsj** [comment]
Hi @bennettrogers, this was changed on https://github.com/django-webpack/webpack-bundle-tracker/pull/91

We still have the `outputChunkDir` variable and we use it:
https://github.com/django-webpack/webpack-bundle-tracker/blob/8a517eea7b30e8ac47ce5a7d2d93eca356fe8e52/lib/index.js#L71

but only if the filename is a relative path:
https://github.com/django-webpack/webpack-bundle-tracker/blob/8a517eea7b30e8ac47ce5a7d2d93eca356fe8e52/lib/index.js#L161-L163

Are you passing a relative filename path? Or does it have a leading `/`?

**Comment by dannyshaw** [comment]
I am also seeing path no longer working, it's always placed in the current directory. absolute paths should be respected should they not?

**Comment by dannyshaw** [comment]
@fjsj There might be some confusion here, the `webpack-stats.json` file seems to not be respecting the `path` option provided in options and is now just writing the stats file in the pwd. Your response seems to be in relation to `publicPath` that's written for each chunk. This is a bug with the path to `webpack-stats.json`

I can confirm I've worked around the bug by using an absolute filename. 
If this is intentional then perhaps the docs need updating?

Broken:
```javascript
new BundleTracker({
  path: OUTPUT_DIRECTORY,
  filename: 'webpack-stats.json'
})
```

Workaround:
```javascript
new BundleTracker({
  filename: path.join(
    OUTPUT_DIRECTORY,
    'webpack-stats.json'
})
```

**Comment by vasili4396** [comment]
same here, upgraded from 0.4.2 to 1.8.0

not a big deal, as a workaround mentioned above is perfectly fine, but d.ts tells me, that I should be able to use this (broken) option, which is confusing

**Comment by fjsj** [comment]
So I think the issue is on [typings.d.ts](https://github.com/django-webpack/webpack-bundle-tracker/blob/8a517eea7b30e8ac47ce5a7d2d93eca356fe8e52/typings.d.ts)
Thanks for reporting @vasili4396 
If you can/want open a PR solving this, please feel free.
