### ISSUE TITLE
move tests to github actions?

### ISSUE THREAD

**Issue by shapiromatron** [django-webpack/webpack-bundle-tracker#112]
Hi noticed all the tests are failing right now. Would you accept a PR moving them to github actions? If so, I could work on it if you'd like.

**Comment by fjsj** [comment]
Yes, please! It would be great to also fix https://github.com/django-webpack/django-webpack-loader

**Comment by amandasavluchinske** [comment]
PRs for this change are merged. Thanks everyone!
