### ISSUE TITLE
Optional chaining breaks compatibility with Node.js version 12

### ISSUE THREAD

**Issue by fsologureng** [django-webpack/webpack-bundle-tracker#118]
https://github.com/django-webpack/webpack-bundle-tracker/blob/0136aec9c6d9b7046ba1e25f396df5e383f401da/lib/index.js#L87

Optional chaining is not supported in Node.js version 12, so this code [has broken declared compatibility](https://github.com/django-webpack/webpack-bundle-tracker#compatibility).

**Comment by fjsj** [comment]
Thanks, at the same time, Node 12 LTS support ended more than 1 year ago. I will update the README.
