### ISSUE TITLE
KeyError in Webpack stats output

### ISSUE THREAD

**Issue by mercadocommerce-r303** [django-webpack/webpack-bundle-tracker#12]
I'm using webpack v 1.13.1 transpiling TypeScript and have webpack-bundle-tracker 0.0.93 which outputs webpack-stats.json such as the following:

`{"status":"error","message":"(3,21): error TS2503: Cannot find namespace 'moment'.","publicPath":"/website/js/"}
`

django-webpack-loader is looking for a key 'error' which isn't present in this output and therefore the page  throws a Python KeyError.

**Comment by robinelvin** [comment]
Raised this as wrong user and can't delete.

**Comment by owais** [comment]
@robinelvin re-open if this is still an issue.

**Comment by robinelvin** [comment]
@owais Yes, this is still an issue. When Typescript compilation has no errors it works fine but when there are errors the output is as described.

**Comment by owais** [comment]
Please re-open if this is still an issue in 1.0.0-alpha.0. PRs welcome.
