### ISSUE TITLE
Missing assets section of webpack-stats in ci github action agent build

### ISSUE THREAD

**Issue by roblatdomain** [django-webpack/webpack-bundle-tracker#124]
#### Issue description
In local build, webpack-stats is good, it looks like:
```
...
"assets": 
    "offers-928c50a.js": {
      "name": "offers-928c50a.js",
      "path": "[hidden]/static/bundles/offers-928c50a.js",
      "publicPath": "/static/bundles/offers-928c50a.js"
    },
...
"chunks": {
    "offers": [
      "offers-928c50a.js"
    ],
}
```
But in ci build, it looks like:
```
... // assets section missing
"chunks": {
    "offers": [
      {
        "name": "offers-928c50a.js",
        "publicPath": "/static/bundles/offers-928c50a.js",
        "path": "[hidden]/static/bundles/offers-928c50a.js"
      }
    ],
}
```
Then in ci tests will emit many weird errors: `TypeError: expected string or bytes-like object`.
My question is what can make that difference?

#### Technical info

<pre>
 Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  npmPackages:
    uglifyjs-webpack-plugin: ^2.2.0 => 2.2.0 
    webpack: 5.58.0 => 5.58.0 
    webpack-bundle-tracker: 2.0.1 => 2.0.1 
    webpack-cli: 4.9.0 => 4.9.0 
</pre>

**Comment by fjsj** [comment]
Where in CI build are you seeing the second case?

**Comment by roblatdomain** [comment]
> Where in CI build are you seeing the second case?

Our ci pipeline will run `yarn build` and generate webpack-stats.json as a part of artifact for download from github: https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts. I found the second case in there.

**Comment by roblatdomain** [comment]
I figured out the reason, there is a `actions/cache@v3` in our pipeline caused that.
