### ISSUE TITLE
Why is filename tracked separately from path?

### ISSUE THREAD

**Issue by jleclanche** [django-webpack/webpack-bundle-tracker#13]
What is the reasoning behind tracking `path` and `filename` separately? It's prone to errors, as `filename` is _always_ a relative path even if it begins with a slash, which means that, for example, `filename: "/var/www/webpack-stats.json"` would be written into `/var/www/var/www/webpack-stats.json` which is extremely counter-intuitive.

**Comment by owais** [comment]
Could you share your full config please?

**Comment by jleclanche** [comment]
https://github.com/HearthSim/HSReplay.net/blob/master/webpack.config.js#L54-L58

**Comment by owais** [comment]
Your config looks fine. `filename` is supposed to be just the name of the file and thus always relative to the `path`. Check https://webpack.github.io/docs/configuration.html

**Comment by jleclanche** [comment]
@owais My config is fine because I fixed it, please see the original issue - the API is redundant and error-prone and I was asking if there's an actual reason behind it.

**Comment by owais** [comment]
In that case you should have shared the config in question. The one that was bad :)

**Comment by jleclanche** [comment]
@owais The config I pasted in the original post reproduces the issue.

**Comment by owais** [comment]
That usage is incorrect. `filename` is appended to `path` by webpack to form the full path. Webpack documentation issue that caused the confusion. We can't remove useful information from manifest to make up for confusing or lack of webpack documentation.

**Comment by jleclanche** [comment]
Where does webpack use those args? All I can find is your own usage here:

https://github.com/owais/webpack-bundle-tracker/blob/master/index.js#L83-L84

**Comment by owais** [comment]
I see. I confused it with the `filename` in `output` section. (sharing full config always helps). Anyway, having both `path` and `filename` is consistent with how webpack defines the path in other places so for someone having used and read webpack docs, this should be intuitive. Other than that it is useful to split the path into a base path and the filename relative to the project. It also gives much more flexibility to create custom tools around the manifest file like for deployments using CI servers. Also makes it easier to keep the manifest file backward compatible. For example, if we want to introduce another stats file to contain more detail info about the build, a different file for errors or multiple files for multiple entries in future, it should be easier to use a common `path` and different `filename` for the files.
