### ISSUE TITLE
What about font and image files?

### ISSUE THREAD

**Issue by mkarajohn** [django-webpack/webpack-bundle-tracker#14]
Currently the `webpack-stats.json` only has entries for `.css` and `.js` files. 

What about font and image files that are outputed by the `file-loader` ? How can I make it so that they are included in the `.json` too?

**Comment by owais** [comment]
They are not included in JSON. In your CSS, you can use relative imports. In JS, you can actually `require()` image files. If you point your static url (static.myapp.com or myapp.com/static) to the root of the directory where you store the output of the bundles then you should be able to guess the names easily.

**Comment by mkarajohn** [comment]
Ok, full disclosure.

I am a front end developer trying to make the rest of my team see that switching from using django with almond and requirejs to django with webpack is better, so I am kind of going rogue here. 

Can I send you an email to have a conversation since I don't think this is the appropriate place for it?

**Comment by owais** [comment]
Sure, we can discuss over email. Closing this ticket.

**Comment by bjackson** [comment]
Hey @mkarajohn, how did you solve this? I'm wanting to use this to grab the imported fontfile paths to stick them in a `Link` header to preload them.
