### ISSUE TITLE
Files included by Context not tracked?

### ISSUE THREAD

**Issue by macolo** [django-webpack/webpack-bundle-tracker#15]
I am trying to include a directory tree in my bundle by adding 

```
// this will import everything inside the static directory into the bundle
// http://stackoverflow.com/questions/27639005/how-to-copy-static-files-to-build-directory-with-webpack
require.context("./static/", true, /^.*/);
```

to the entry point `main.js`.

However these files (images) are not in the `webpack-stats.json`, even though they are successfully included in the bundle.

Am I missing something?

BTW this is used for a Django setup with https://github.com/owais/django-webpack-loader where I would like to include all images with `{% webpack_static 'img/logo.png' %}` so that I can set an infinite expiry date on all static resources in the webserver.

This is how the webpack-stats.json looks like:

```
{
  "status": "done",
  "chunks": {
    "main": [
      {
        "name": "main-8c8d3a3fe3a2a9478630.js",
        "path": "/Users/mario/Projects/getmyski/assets/dist/main-8c8d3a3fe3a2a9478630.js"
      },
      {
        "name": "main-8c8d3a3fe3a2a9478630.css",
        "path": "/Users/mario/Projects/getmyski/assets/dist/main-8c8d3a3fe3a2a9478630.css"
      },
      {
        "name": "main-8c8d3a3fe3a2a9478630.js.map",
        "path": "/Users/mario/Projects/getmyski/assets/dist/main-8c8d3a3fe3a2a9478630.js.map"
      },
      {
        "name": "main-8c8d3a3fe3a2a9478630.css.map",
        "path": "/Users/mario/Projects/getmyski/assets/dist/main-8c8d3a3fe3a2a9478630.css.map"
      }
    ]
  }
}
```

**Comment by macolo** [comment]
I just noticed that this is beyond the scope of the current implementation.

What would have to be done:

Add the original filename and relative path to the json:
https://github.com/webpack/docs/wiki/how-to-write-a-plugin#exploring-assets-chunks-modules-and-dependencies

Then update the template tag to look up the original filename and path and output the hashed filename with the static-url path here https://github.com/owais/django-webpack-loader/blob/master/webpack_loader/templatetags/webpack_loader.py

I think it would be quite interesting to have this working so that all static resources can be managed in webpack (including, for example image optimisation).

On the other hand there is also https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#manifeststaticfilesstorage and thumbnails applications (https://www.google.ch/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=django%20thumbnails). 

What are the pro / cons of each solution?

**Comment by owais** [comment]
Is this something that is still desired? We can try to add it in 1.0 if someone can come up with a proposal describing what the feature should look like. 1.0 will only support webpack >4.0
