### ISSUE TITLE
bundle tracker is not working with code splitting at webpack 2

### ISSUE THREAD

**Issue by alexfqc** [django-webpack/webpack-bundle-tracker#19]
When you run webpack 2 to split react routes code or make lazy loading, the webpack-stats.json does not match to files 0.js, 1.js and etc.

A sample for react lazy loading is here: https://webpack.js.org/guides/lazy-load-react/

and for react routes: https://brotzky.co/blog/code-splitting-react-router-webpack-2/

**Comment by alexfqc** [comment]
I've modified the index.js at root to work with webpack2 code splitting:

Plugin.prototype.apply = function(compiler) {
    var self = this;

    compiler.plugin('compilation', function(compilation, callback) {
      compilation.plugin('failed-module', function(fail){
        var output = {
          status: 'error',
          error: fail.error.name || 'unknown-error'
        };
        if (fail.error.module !== undefined) {
          output.file = fail.error.module.userRequest;
        }
        if (fail.error.error !== undefined) {
          output.message = stripAnsi(fail.error.error.codeFrame);
        }
        self.writeOutput(compiler, output);
      });
    });

    compiler.plugin('compile', function(factory, callback) {
      self.writeOutput(compiler, {status: 'compiling'});
    });

    compiler.plugin('done', function(stats){
      if (stats.compilation.errors.length > 0) {
        var error = stats.compilation.errors[0];
        self.writeOutput(compiler, {
          status: 'error',
          error: error['name'] || 'unknown-error',
          message: stripAnsi(error['message'])
        });
        return;
      }

      **var chunks = {
        "split": []
      };
      var fileName = '';
      stats.compilation.chunks.map(function(chunk){
        var files = chunk.files.map(function(file){
          fileName = file;
          var F = {name: file};
          
          if (compiler.options.output.publicPath) {
            F.publicPath= compiler.options.output.publicPath + file;
          }
          if (compiler.options.output.path) {
            F.path = path.join(compiler.options.output.path, file);
          }
          return F;
        });

        // chunks[chunk.name] = files;
        if(chunk.name !== null){
          chunks[chunk.name] = files;
        }
        else{
          var split = chunks["split"];
          split.push(files[0]);
          chunks["split"] = split;
        }
      });**
      
      var output = {
        status: 'done',
        chunks: chunks
      };

      if (self.options.logTime === true) {
        output.startTime = stats.startTime;
        output.endTime = stats.endTime;
      }

      self.writeOutput(compiler, output);
    });
};

The part in bold is the modified code.

With this code, if webpack splits js code, you must add {% render_bundle 'split' %} at index.html

I do not if this solution is a workaround, please let me know if is correct or if there is another way to solve this problem.

Thanks in advance.

**Comment by SGudbrandsson** [comment]
We managed to fix this a little bit easier with this - #23

**Comment by owais** [comment]
@melck has contributed webpack4 support. We are working towards a 1.0 which will only support webpack >4. I've published `1.0.0-alpha.0`. Let us know if this version fixes the problem.
