### ISSUE TITLE
Gzipped bundles are not being tracked

### ISSUE THREAD

**Issue by x8lucas8x** [django-webpack/webpack-bundle-tracker#22]
Gzipped bundles compressed with webpack-compressor-plugin are not being tracked and, therefore, not available in the json output.

**Comment by lazorgator** [comment]
Also experiencing this issue with the release grabbed from pip, version 0.5.0

**Comment by jamesmgg** [comment]
So... what's the solution for this?

**Comment by x8lucas8x** [comment]
@jamesmgg I ended doing compression on nginx level, which I believe is what most people do. Since then I haven't tried using webpack for this purpose again.

**Comment by jamesmgg** [comment]
Yeah, I ended up doing it at the django level too. In production it
automatically knows to search for js.gz files when requesting a js file.

**Comment by lnq56789** [comment]
@jamesmgg Hi, may I ask how did you do that?

**Comment by owais** [comment]
If this is still helpful, please let us know over at #52
