### ISSUE TITLE
stats for "commons.chunk.[hash].js" doesn't remove the `[hash]` for it's key

### ISSUE THREAD

**Issue by pconerly** [django-webpack/webpack-bundle-tracker#3]
Hi, this is a great project, and great [write-up](http://owaislone.org/blog/webpack-plus-reactjs-and-django/) about all of this! 

Just ran into some funkiness: when I have a `webpack.config.js` like:

``` js
  plugins: [
      new webpack.optimize.CommonsChunkPlugin("commons.chunk.[hash].js"),
      new BundleTracker({path: BUILD_ROOT, filename: './webpack-stats.json'}),
  ],
```

I get output in `webpack-stats.json` like:

``` js
    "commons.chunk.[hash].js": [
      {
        "name": "commons.chunk.3c5952bfdfd9e5d8fca5.js",
        "publicPath": "_\/static\/js\/commons.chunk.3c5952bfdfd9e5d8fca5.js",
        "path": "\/Users\/peterconerly\/src\/picmonkey\/build\/website\/js\/commons.chunk.3c5952bfdfd9e5d8fca5.js"
      }
    ]
```

It's kind of weird, it feels like it should be omitting the `[hash]` in the key.  And probably the `.js` too, to be consistent with how pages are generated.

I'm using your [django plugin](https://github.com/owais/django-webpack-loader/), so that means that my `render_bundle` ends up looking like:

``` djhtml
{% load render_bundle from webpack_loader %}

{% render_bundle 'commons.chunk.[hash].js' %}
{% render_bundle 'index_module' %}
```

So everything works, it just looks kind of odd and feels like it might be an oversight.

**Comment by owais** [comment]
Yes, it does look weird. I don't think this should be because of webpack-bundle-tracker as webpack hands it the bundle names as they come. 

If you can share you full (as much as possible) webpack config, I'll try to run it locally and fix the thing if possible. May be even add an example for using CommonChunkPlugin

**Comment by pconerly** [comment]
Ahhh---- yeah, I was giving a simple configuration to `CommonsChunkPlugin` which was the issue.

When I changed my plugin config to be:

``` js
  plugins: [
      new webpack.optimize.CommonsChunkPlugin({
        name: 'commons.chunk', 
        filename: "commons.chunk.[hash].js"}),
      new BundleTracker({path: BUILD_ROOT, filename: './webpack-stats.json'}),
  ],
```

I get this in my `webpack-stats.json`

```
    "commons.chunk": [
      {
        "name": "commons.chunk.d37cb74b29d89c037db2.js",
        "publicPath": "\/_\/static\/js\/commons.chunk.d37cb74b29d89c037db2.js",
        "path": "\/Users\/peterconerly\/src\/picmonkey\/build\/website\/js\/commons.chunk.d37cb74b29d89c037db2.js"
      }
    ]
```

So that is much better!

**Comment by owais** [comment]
BTW, you don't need to and should not store webpack-stats.json in static assets. I'm assuming you do that because of BUILD_ROOT in your config. You can do this, just that it is not needed as you don't need to serve them as static assets.
