### ISSUE TITLE
Expose entrypoints/chunk assocation for Webpack 4

### ISSUE THREAD

**Issue by beheh** [django-webpack/webpack-bundle-tracker#31]
Webpack 4 removes the CommonsChunkPlugin and lets Webpack itself decide how to do code splitting (using the splitChunks and cacheGroups settings). This results in combined chunks  as Webpack sees fit, possibly (entrypoints `pageA` and `pageB` result in three chunks: `pageA` + `pageB` + `pageA~pageB`).

As we no longer know which chunks to include for all code required for a specific entrypoint, we really should just be able pass in the entrypoints to any downstream tool such as django-webpack-loader.

Therefore, this plugin should ideally start exposing the entryPoint/chunk associations, similar to `webpack --profile`:

```
"entrypoints": { "Homepage": { "chunks": [ 0, 1, "Homepage" ], "assets": [ "0-de629161af8ff152d740.js", "1-de629161af8ff152d740.js", "Homepage-de629161af8ff152d740.js" ] },
```

django-webpack-loader can then just be instructed to `{% render_bundle "Homepage" %}` and load the three chunks `0`, `1` and `Home`.

Refs owais/django-webpack-loader#157.

**Comment by beheh** [comment]
So, I've built [a prototype](https://github.com/beheh/webpack-bundle-tracker) that uses the entrypoints property from the webpack compilation results. The remaining question now is, how exactly do we propagate this in the stats file to downstream apps (such as django-webpack-loader)? I see a few possibilites:

1. __Replace the `chunks` property__  
This should work straight out of the box and not require any changes to downstream. This unfortunately does break any templates where dependant bundles are explicitely rendered. In my codebase for example, we've so far used two `render_bundle` calls on a single page to load a `vendor` bundle and an actual `site` bundle respectively. By using entrypoints, there should be no more need to include the vendor bundle explicitely as it'll be picked up as part of the `site` entrypoint, so I'll need to drop the `render_bundle`. This would be a breaking change.

2. __Add a new `entrypoints` property__  
We could simply augment the stats file with a separate entrypoints property. django-webpack-loader could then either release an update, changing `render_bundle` to use the `entrypoints` property instead of `chunks`, but that would still be a breaking change for the same reasons as above. As an alternative, one could add a new command, i.e. `render_entry` to automatically render an entrypoint. This would be backwards compatible.

There's a few more open questions, such as: how does one deduplicate chunks on a page? If I have two entires, `moduleA` and `moduleB`, and both depend on chunk `vendor`, including both on a page would result in a duplicate `vendor` script tag. Maybe `render_entry` should be able to take a variable amount of entries, and deduplicate among them? But then, how do we handle things like the `css` flag?

**Comment by bashlyss** [comment]
I'm coming across this issue as well, a related issue filed in the main webpack repo that has a workaround is https://github.com/webpack/webpack/issues/6797.

That said, I should be able to just mark `splitChunks: 'all'` and have it just work

For those too lazy to read through the thread above, `splitChunks: 'async'` works with 0.4.0-beta to load bundles with django-webpack-loader.

Given webpack 4 support is in beta anyways, a breaking change to make it 'just work' for people migrating later I think would be a reasonably safe change, if we expose all the chunks as before it could be non-breaking but load content multiple times as a safer alternative

**Comment by SmileyChris** [comment]
@beheh, i like your prototype. IMO I'd stick with the second option -- a new `entrypoints` property. Couldn't this just contain an object with the entrypoints as keys and an array of chunks that match, rather than adding the files to this section too?

As to how django-webpack-loader integrates it: personally I'd add new tags that would compile the chunks to render, then a separate tag to render all the compiled chunks which can consider deduplication:
```django
{# Build the chunks with: #}
  {% webpack_entrypoint 'some-entry' %}
  {# and/or #}
  {% webpack_chunk 'some-chunk' %}
{# Then render them with: #}
  {% render_webpack %}
  {# or #}
  {% render_webpack css %} ... {% render_webpack js %}
```

**Comment by n6g7** [comment]
I'm running into this as well, @owais are there any plans for bringing something like this into the lib?

**Comment by owais** [comment]
webpack4 support is in master now and was contributed by @melck. I'm assuming this was resolved by adding webpack4 support? If not, feel free to re-open and/or send a PR.
