### ISSUE TITLE
Required version of dependency deep-extend contains a security vulnerability.

### ISSUE THREAD

**Issue by GrimzEcho** [django-webpack/webpack-bundle-tracker#33]
After npm installation of the current version (0.3.0), npm gives the following warning after running `npm audit`.

Some vulnerabilities require your attention to resolve:
Low:                         Prototype Pollution
Package:                  deep-extend
Patched in:               >=0.5.1
Dependency of:        webpack-bundle-tracker
More info:                 https://nodesecurity.io/advisories/612                  

I think that the version of deep-extend needs to be upgraded from 0.4.1 and repackaged. Manually upgrading deep-extend didn't seem to cause any problems, but I only have a small project and didn't test.

**Comment by nemani** [comment]
Need this too!

**Comment by migcarva** [comment]
Would appreciate this dep update as well. Any issue holding this back?

**Comment by b1tst0rm** [comment]
Any update on this?

**Comment by ccsv** [comment]
Can you guys do a pull request of just updating it and see what breaks in dev?

**Comment by migcarva** [comment]
There's already [one](https://github.com/owais/webpack-bundle-tracker/pull/32).

**Comment by shanonvl** [comment]
FYI all, there's a new release that resolves this issue: https://github.com/owais/webpack-bundle-tracker/pull/38
