### ISSUE TITLE
Consuming the stats file

### ISSUE THREAD

**Issue by magnusriga** [django-webpack/webpack-bundle-tracker#35]
I am trying to access the name of one bundle in another bundle, and thought the stats file might be used for that.

The problem however, is that the stats file is only written to dist, so when requiring/importing it in one of my bundles, webpack crashes:

> Module not found: Error: Can't resolve './stats.json'

Any idea how this can be fixed? Perhaps only read the file runtme somehow?

**Comment by owais** [comment]
Interesting use case. My intention was only to allow other processes consume bundles generated by webpack. Never intended the library to allow a different plugin in the same webpack process to consume the stats file so I don't think we'd add features to enable this case but if you or someone has a simple/clean proposal that enables this without making the actual use case more complex, I think we can add it.

**Comment by owais** [comment]
Closing for now.
