### ISSUE TITLE
Upgrade deep-extend package to fix vulnerability

### ISSUE THREAD

**Issue by nwshane** [django-webpack/webpack-bundle-tracker#39]
Running `npm audit` (with npm 6) for webpack-bundle-tracker v0.3.0 shows it has a vulnerability caused by the deep-extend package: ![deep-extend vulnerability](https://user-images.githubusercontent.com/4259159/45324070-1c662200-b51b-11e8-84f1-9399dec0ae15.png) Would be great to update deep-extend and fix the vulnerability.

**Comment by shanonvl** [comment]
FYI this is done: https://github.com/owais/webpack-bundle-tracker/pull/38
