### ISSUE TITLE
fixed Path

### ISSUE THREAD

**Issue by n3ssi3** [django-webpack/webpack-bundle-tracker#4]
I have a question / feature request.

Is it possible to have the webpack-stats.json relative path instead of the full path?

I am sharing my project with other developers, and not all of them have NPM installed. So I want to have the lastest version of the bundle in my git repository.
Is there a good way to do that?

**Comment by levic** [comment]
We were doing this by extending the `BundleTracker` plugin:

``` js
    var RelativeBundleTracker = function(options) {
        BundleTracker.call(this, options);
    };
    RelativeBundleTracker.prototype = Object.create(BundleTracker.prototype);
    RelativeBundleTracker.prototype.writeOutput = function(compiler, contents) {
        var relativePathRoot = path.join(__dirname) + path.sep;
        _.forIn(contents.chunks, (bundle) => {
            _.forEach(bundle, (chunk) => {
                if (chunk.path.startsWith(relativePathRoot)) {
                    chunk.path = chunk.path.substr(relativePathRoot.length);
                }
            });
        });
        //contents.relativePathRoot = relativePathRoot;
        BundleTracker.prototype.writeOutput.call(this, compiler, contents);
    };
...
    plugins: [
        new RelativeBundleTracker({ filename: '.' + outputPath + 'webpack-stats.json', indent: 2 }),
    ],
```

A simpler and more general solution might be to allow for passing of a callback that can do any modifications you want to the contents that is about to be written.

**Comment by darkowic** [comment]
I dont get it why this feature request is closed. I use the same workaround like @levic for half of year currently...

**Comment by owais** [comment]
Fixed in https://github.com/owais/webpack-bundle-tracker/pull/29
