### ISSUE TITLE
When is version 0.4 ready to leave beta?

### ISSUE THREAD

**Issue by haakenlid** [django-webpack/webpack-bundle-tracker#42]
According to my `npm outdated` the `@latest` of webpack-bundle-tracker is 0.4.2-beta. 

I would like to upgrade because of issue #27 and #33, but I assume that the beta version is not ready for production, so I'm using version 0.3

**Comment by dpipchenko** [comment]
Any updates on this please?

**Comment by RaphaelKimmig** [comment]
@owais Is there anything one could do to help getting 0.4 released?

**Comment by owais** [comment]
Published 0.4.3
