### ISSUE TITLE
Need maintainers?

### ISSUE THREAD

**Issue by tony** [django-webpack/webpack-bundle-tracker#46]
(First, my apologies, I don't want to derail the thread at #41.)

In this case, there are two projects dependent on each other, and compatibility with old versions can't break. This would take a lot of time for @owais to QA.

In addition, there are different versions of webpack and there could be variations in between those.

@owais Would it be helpful to have more contributors / maintainers? Any updates as to how busy you are / if you're using this in production and can support it?

In my personal case: I'm using Django 2.2 with Webpack v4 (with codesplitting), so this lead me to issues that haven't been merged yet here and https://github.com/owais/django-webpack-loader

**Comment by owais** [comment]
Hi Tony, I'm still quite busy with my current job (and life) and as a result haven't had a lot of time to look into this. Both packages have suffered in the sense that they haven't been updated to work perfectly with newer version of webpack. One of the original goals of this project was to abstract away the ever changing face of node/webpack/JS ecosystem so Django projects could always integrate with the latest node tech without having to make code changes all the time. To that end having webpack 4 compatibility is a must have for these two projects. 

I've actually been talking to @arshsingh to help maintain these libraries and would be open to anyone else wanting to contribute but not sure how to do that without first spending a lot of time reviewing PR from people :)

I'll try to take out some time soon and come up with a plan to move towards webpack 4 without breaking projects that work now.

**Comment by tony** [comment]
@owais Understood on being busy, yeah

It'd be nice having someone like @arshsingh around to help here

Idea 1: It may be worth considering the possibility of maintaining a separate branch for webpack v2/3, that's maintenance-only, then having master be webpack v4+.

That way there's less worry about breaking old webpack versions in master.

To my knowledge, the issues regarding splitChunks and stuff are primarily for webpack v4+ users.

Idea 2: This depends on how busy things are since it's a drastic step to switch orgs . Have you considered @jazzband? They have the concept of being able to maintain (mostly django) packages where its easy to merge in PRs and package. (personally on my projects, I didn't go that far, I just moved them to their own organization and added maintainers)

> plan to move towards webpack 4 without breaking projects that work now.

That's where a lot of the stress comes from. Exactly (not breaking support for older webpack versions). Once I moved my stuff to webpack v4, the whole ecosystem of plugins I used ended up changing.

**Comment by melck** [comment]
@owais Any news on this subject ? I also use django-webpack-loader. I think they would be many improvement to do. How can we contribute ? I saw you haven't time to review PR and now i think they are outdated.

I was thinking to begin by write tests for every supported version of Webpack.

**Comment by owais** [comment]
@melck  Starting with writing tests for different versions and may be having branches for older versions as @tony suggested sounds like a good plan. I'd be happy to accept PRs that take us closer to this goal and eventually handing over to a handful of maintainers.

//cc @arshsingh @tony

**Comment by tony** [comment]
@owais Any opinion on jazzband? That is *very* liberal scope of maintainers since effectively any jazzband member can contribute

But the issue is it's hard for me to join as a full maintainer end to end, I tend to only need to contribute when there's a version lapse in webpack/another dependency

Also thanks for bringing up writing tests for different versions with @melck in #47. On that note though, we can also start cutting out older versions and refer them to an earlier one. (perhaps make a branch to cut compatibility off so bug fixes can still make it in)

**Comment by owais** [comment]
Just checked out Jazzband. It's an interesting idea but not sure if we should off-load to them yet. I think it's better that we add support for webpack4 here and in django-webpack-loader first to give the project a direction about how to handle future changes and may be then involve a wider community.

**Comment by fjsj** [comment]
Closing this as @vintasoftware is now maintaining this package and https://github.com/django-webpack/django-webpack-loader
