### ISSUE TITLE
Question: Can output be outside of the package folder?

### ISSUE THREAD

**Issue by lorinkoz** [django-webpack/webpack-bundle-tracker#64]
I am using `webpack-bundle-tracker` in conjunction with `django-webpack-loader`. My folder structure looks like:

```
project/
    django_project/
    react_project/
```

I had my bundle tracker configured to ouput the stats file outside the package itself, like: `../django_project/webpack-stats.json`. The reason for doing this is that I wanted to include the `webpack-stats.json` in my Dockerfile which lives inside `django_project`.

I have updated a number of dependencies today, including `webpack-bundle-tracker` to `1.0.0-alpha.1`. I noticed that the stats file is no longer getting output outside the `react_project` folder, no matter how many double dots (`..`) I prepend in the bundle tracker filename.

- Is this intentional?
- Is this a decision of this package? (could also be something from another package I updated)
- Any elegant way to overcome this?

Thanks!

**Comment by elramus** [comment]
I think I ran into the same problem today as well. Used this in a previous Django project, at `0.4.3`. Went to use the same stack on a new project with version `1.0.0-alpha.1` and I couldn't get `webpack-stats.json` to get created where I wanted. Same webpack config settings. In my case I was trying to just get it in the root of the Django project folder, not outside of it. Rolling back to `0.4.3` solved it.

**Comment by andersk** [comment]
#53 changed the interpretation of `filename` to be relative to the Webpack `output.path` option if `path` is not set. This may change the number of `..`s you need to escape the project root, but it should still be possible. Could this be what you’re seeing?
