### ISSUE TITLE
Ensure ordering of keys in JSON output

### ISSUE THREAD

**Issue by dolan-a** [django-webpack/webpack-bundle-tracker#69]
I've found that the ordering of keys is not guaranteed when outputting the stats file, and this doesn't work well with storing the JSON file in a version control system (i.e., git) since the file can change with subsequent runs of building.

This [SO post](https://stackoverflow.com/questions/16167581/sort-object-properties-and-json-stringify) has several solutions for ensuring the order, such as sorting things before calling `JSON.stringify` or using a 3rd party library, `json-stable-stringify`.  

Is this something you'd support adding?

**Comment by fjsj** [comment]
Released at 1.7.0
