### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by gilmrjc** [django-webpack/webpack-bundle-tracker#89]
The django-webpack-loader package is already using in the 1.0.0 version (https://github.com/django-webpack/django-webpack-loader/pull/269). What does this package need for a stable release? How can I help?

**Comment by fjsj** [comment]
We just merged the release PR: https://github.com/django-webpack/webpack-bundle-tracker/pull/90

Thanks!

**Comment by gilmrjc** [comment]
Thank you for maintaining this package 😄
