### ISSUE TITLE
Issue when using BundleTracker for multiple webpack configuration

### ISSUE THREAD

**Issue by TomekStaszkiewicz** [django-webpack/webpack-bundle-tracker#96]
I am in process of upgrading the webpack to v5. I encountered an issue after upgrading `webpack-bundle-tracker`.
When I export multiple configurations from webpack config - [it is a feature introduced in webpack 3 ](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations) the new version of `webpack-bundle-tracker` does not work as expected. It randomly chooses only one configuration and creates stats for it.
I use webpack5 and the issue occurs only on `webpack-bundle-tracker1.0.0`. I checked on version `v0.4.3` and it works as expected. 

[I created a small reproduction for you](https://github.com/TomekStaszkiewicz/bundle-tracker-reproduction/)

**Comment by fjsj** [comment]
Closed via #98, thanks!
